[package]
name = "rlox"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = { version = "0.5.1", features = ["auto-color"] }
clap = { version = "4.5.42", features = ["derive", "unicode"] }
ordered-float = "5.0.0"
rustyline = "17.0.0"
thiserror = "2.0.12"
